# An Ingress with 2 hosts and 3 endpoints
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rules2
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-v1
          servicePort: 30303
