apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: tomcat-port
    protocol: TCP
  selector:
    app: tomcat
  type: NodePort
